# name指的是这套工作流程的名称，可以自定义
name: CI

# on是指这套工作流程的trigger条件，即在push时触发
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs就是这套工作流程了
jobs:
  # build相当于<job_id>,可以自定义
  build:
    # 指定该job_id下的运行环境
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 先将仓库的代码checkout到环境中，github提供了checkout的方法，只需要我们加上这条即可
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
